/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        display: ['Syne', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      colors: {
        background: 'var(--background)',
        'panel-left': 'var(--panel-left)',
        'panel-right': 'var(--panel-right)',
        foreground: 'var(--foreground)',
        muted: 'var(--muted)',
        accent: 'var(--accent)',
        'accent-yellow': 'var(--accent-yellow)',
        border: 'var(--border)',
        "tertiary-fixed-dim": "#b9c7df",
        "on-tertiary-fixed-variant": "#3a485b",
        "secondary-fixed": "#ffdcc3",
        "on-secondary-fixed-variant": "#6e3900",
        "secondary-fixed-dim": "#ffb77d",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline-variant": "#bcc9c6",
        "surface-container": "#eceef0",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d5e3fc",
        "on-tertiary-container": "#fdfcff",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#2f1500",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "on-error": "#ffffff",
        "surface": "#f7f9fb",
        "on-primary-container": "#f4fffc",
        "on-tertiary-fixed": "#0d1c2e",
        "primary-container": "#008378",
        "secondary": "#904d00",
        "secondary-container": "#fe932c",
        "inverse-primary": "#6bd8cb",
        "tertiary": "#4f5d71",
        "on-primary-fixed-variant": "#005049",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed": "#89f5e7",
        "outline": "#6d7a77",
        "on-surface-variant": "#3d4947",
        "surface-container-high": "#e6e8ea",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "primary": "#00685f",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "on-primary-fixed": "#00201d",
        "surface-tint": "#006a61",
        "error": "#ba1a1a",
        "stitch-background": "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "primary-fixed-dim": "#6bd8cb",
        "tertiary-container": "#67758b",
        "error-container": "#ffdad6",
        "on-secondary-container": "#663500"
      }
    },
  },
  plugins: [],
}
